repos:
  - repo: https://github.com/psf/black
    rev: '23.12.0'  # Use a specific version or 'stable' for the latest
    hooks:
      - id: black
        language_version: python3  # Specify your Python version

  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'  # Use a specific version
    hooks:
      - id: isort
        language_version: python3  # Specify your Python version

  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # Use the latest version
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/pylint
    rev: 'v3.0.3'  # Use the latest version
    hooks:
      - id: pylint
        args: ['--errors-only']  # Optional: only show errors

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        description: This hook formats C/C++ files with clang-format.
        entry: clang-format -i -style=google
        language: system
        files: '\.(cpp|h|hpp|c)$'
