[build-system]
requires = [
    "setuptools>=42",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"


[tool.cibuildwheel]
test-command = "python {project}/tests/test.py"
enable = ["pypy", "graalpy"]
build-frontend = "build[uv]"

[[tool.cibuildwheel.overrides]]
select = ["gp311_242-win_amd64"]
repair-wheel-command = ""


[tool.ruff]
show-fixes = true
target-version = "py39"

[tool.ruff.lint]
extend-select = [
  "B",   # flake8-bugbear
  "I",   # isort
  "PGH", # pygrep-hooks
  "RUF", # Ruff-specific
  "UP",  # pyupgrade
]
