package:
  name: python_example
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: |
    # This is a total hack because we are not using conda-forge pybind11. Remove after 2.6.0.
    # And never do this yourself unless you know what you are doing (it
    # explicitly is okay with pybind11, but may not be with arbitrary
    # libraries)
    python -m pip install -vvv "git+https://github.com/pybind/pybind11.git@master"
    python -m pip install . -vvv --no-deps
    python -m pip uninstall -y pybind11

requirements:
  build:
    - {{ compiler('cxx') }}
    # This is a hack because we are not using conda-forge pybind11. Remove after 2.6.0
    - cmake

  host:
    - python
    - pip
    # Disabled for now - pybind11
    # We are requiring a version newer than the latest release

  run:
    - python


test:
  imports:
    - python_example
  source_files:
    - tests
  commands:
    - python tests/test.py

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
